### ISSUE TITLE
Startup script does not look right

### ISSUE THREAD

**Issue by dld2517** [ramsey/docker-pennmush#1]
When the PennMUSH container starts to copy the files to the Volume I have mounted to /mush/game it says

cp: cannot create regular file '/mush/game/./CONNLOG.md': Permission denied
,cp: cannot create regular file '/mush/game/./README': Permission denied
,cp: cannot create regular file '/mush/game/./access.README': Permission denied
,cp: cannot create regular file '/mush/game/./alias.cnf': Permission denied
,cp: cannot create regular file '/mush/game/./aliascnf.dst': Permission denied
,cp: cannot create directory '/mush/game/./data': Permission denied
,cp: cannot create regular file '/mush/game/./getdate.README': Permission denied
,cp: cannot create regular file '/mush/game/./getdate.template': Permission denied
,cp: cannot create symbolic link '/mush/game/./info_slave': Permission denied
,cp: cannot create directory '/mush/game/./log': Permission denied
,cp: cannot create regular file '/mush/game/./mush.cnf': Permission denied
,cp: cannot create regular file '/mush/game/./mushcnf.dst': Permission denied
,cp: cannot create regular file '/mush/game/./names.cnf': Permission denied
,cp: cannot create regular file '/mush/game/./namescnf.dst': Permission denied
,cp: cannot create symbolic link '/mush/game/./netmush': Permission denied
,cp: cannot create regular file '/mush/game/./restart': Permission denied
,cp: cannot create regular file '/mush/game/./restart.dst': Permission denied
,cp: cannot create regular file '/mush/game/./restrict.cnf': Permission denied
,cp: cannot create regular file '/mush/game/./restrictcnf.dst': Permission denied
,cp: cannot create directory '/mush/game/./save': Permission denied
,cp: cannot create symbolic link '/mush/game/./ssl_slave': Permission denied
,cp: cannot create directory '/mush/game/./txt': Permission denied
,cp: preserving times for '/mush/game/.': Operation not permitted
,
Notice that the files are trying to be copied into the "." dot folder. That does not appear to be a valid operation. I have mounted the Volume into another Docker container and verified that I have write access to it. I created a file in the volume.

**Comment by dld2517** [comment]
I resolved this issue by directly pointing to /usr/bin/entrypoint.sh as my startup command.

**Comment by ramsey** [comment]
Glad you were able to resolve it. I'm curious what the full command was that you were trying to run. You shouldn't have to point directly to `/usr/bin/entrypoint.sh`. It should already do that for you.
