### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Routhinator** [ramsey/docker-pennmush#5]
Hi there, I have some questions for the project maintainers. 

I was looking at the dockerfile you have here to see about making a PennMUSH+ASpace container. I wanted to see if I could use this as a base and the following questions came up:

1. Is there any reason build tools are still needed after Pennmush is built? Could the built artifacts not be copied to a new base container without the build-utils to minimize the size of the container?
2. Why is the custom curl build needed? Is this a PennMUSH requirement?

**Comment by ramsey** [comment]
1. There's no reason the build tools need to stick around after PennMUSH is built. I'm not sure the best way to determine what's safe to remove and what isn't. I don't think the binary is static; I think it links to shared libraries, so if the system doesn't have those libraries in their correct, binary-compatible versions, then moving the binary to a different container won't work.
2. When I initially created this, it was on an Alpine image, which had a really old version of cURL in their repositories. I recall there being a more specific reason I chose to do this, but I can't remember what it was.

**Comment by Routhinator** [comment]
Thanks, I will close this to keep things clean. 

Seems that the custom curl could be dropped. I'll investigate the idea of using a second `FROM` in the Dockerfile and copying the build artifacts into a clean container. If I have something PR worthy I'll open it up.

**Comment by ramsey** [comment]
Thanks!
